package:
  name: "multitaper"
  version: "1.0.4c"

source:
  git_url: https://github.com/gaprieto/multitaper

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - jupyter
    - ipykernel
    - requests

about:
  home: https://github.com/gaprieto/multitaper
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Multitaper codes translated into Python"

